export const certificateData=[{
    id:'PUSTOVAYAELENAcer1',
    subject:'на  30 сеансов массажа',
    giver:'Пустового Михаила Сергеевича',
    resiver:'Пустовой Елене Анатольевне',
    resiverIP:'Пустовоая Елена Анатольевна',
    purpose:" подтверждает что она может получить услугу массажа от гражданина:",
    validFrom:'28.11.2020',
    validTo:'28.11.2021',
    conditionsTitle:"в соответствии с нижеперечисленными условиями:",
    conditions:[
        'Сеанс не должен превышать 15 минут;',
        'Выполняться в свободное от основной деятельности время (работа,сон);',
        'Количество одновременно полученных сеансов не должно превышать четырех.'],
    cupons:[
    {name:'Сеанс №1',done:false},
    {name:'Сеанс №2',done:false},
    {name:'Сеанс №3',done:false},
    {name:'Сеанс №4',done:false},
    {name:'Сеанс №5',done:false},
    {name:'Сеанс №6',done:false},
    {name:'Сеанс №7',done:false},
    {name:'Сеанс №8',done:false},
    {name:'Сеанс №9',done:false},
    {name:'Сеанс №10',done:false},
    {name:'Сеанс №11',done:false},
    {name:'Сеанс №12',done:false},
    {name:'Сеанс №13',done:false},
    {name:'Сеанс №14',done:false},
    {name:'Сеанс №15',done:false},
    {name:'Сеанс №16',done:false},
    {name:'Сеанс №17',done:false},
    {name:'Сеанс №18',done:false},
    {name:'Сеанс №19',done:false},
    {name:'Сеанс №20',done:false},
    {name:'Сеанс №21',done:false},
    {name:'Сеанс №22',done:false},
    {name:'Сеанс №23',done:false},
    {name:'Сеанс №24',done:false},
    {name:'Сеанс №25',done:false},
    {name:'Сеанс №26',done:false},
    {name:'Сеанс №27',done:false},
    {name:'Сеанс №28',done:false},
    {name:'Сеанс №29',done:false},
    {name:'Сеанс №30',done:false},
]
},
{
    id:'PUSTOVAYAELENAcer2',
    subject:'на исполнение любого желания',
    giver:'Пустовому Михаилу Сергеевичу',
    resiver:'Пустовой Елене Анатольевне',
    resiverIP:'Пустовоая Елена Анатольевна',
    purpose:" подтверждает, что она может загадать гражданину",
    conditionsTitle:"любое желание в соответствии с нижеперечисленными условиями:",
    validFrom:'28.11.2020',
    validTo:'28.11.2021',
    wish:'',
    conditions:[
        'Желание должно быть сокровенным и искренним;',
        'Не наносить вреда здоровью и психике;',
        'Требуемый срок исполнения желания не должен превышать две недели;',
        'Должно быть осуществимо по материальным и физическим возможностям исполнителя;',
        'Неизменно на протяжении всего процесса его осуществления;',
        'Иметь отношение непосредственно к владельцу сертификата.',
    ],
    cuponsDone:[],    
    certificateDone:false
},{
    id:'cer',
    subject:'на  желание',
    giver:'Пустового Михаила Сергеевича',
    resiver:'Пустовой Елене Анатольевне',
    resiverIP:'Пустовоая Елена Анатольевна',
    purpose:" подтверждает",
    validFrom:'28.11.2020',
    validTo:'28.11.2021',
    conditionsTitle:"в соответствии с нижеперечисленными условиями:",
    conditions:[
        'Сеанс не должен превышать 15 минут;',
        'Выполняться в свободное от основной деятельности время (работа,сон);',
        'Количество одновременно полученных сеансов не должно превышать четырех.'],
    cupons:[
        {name:'Сеанс №1',done:true},
        {name:'Сеанс №2',done:true},
        {name:'Сеанс №3',done:true},
        {name:'Сеанс №4',done:true},
        {name:'Сеанс №5',done:true},
        {name:'Сеанс №6',done:true},
        {name:'Сеанс №7',done:true},
        {name:'Сеанс №8',done:true},
        {name:'Сеанс №9',done:true},
        {name:'Сеанс №10',done:true},
        {name:'Сеанс №11',done:true},
        {name:'Сеанс №12',done:true},
        {name:'Сеанс №13',done:true},
        {name:'Сеанс №14',done:true},
        {name:'Сеанс №15',done:true},
        {name:'Сеанс №16',done:false},
        {name:'Сеанс №17',done:false},
        {name:'Сеанс №18',done:false},
        {name:'Сеанс №19',done:false},
        {name:'Сеанс №20',done:false},
        {name:'Сеанс №21',done:false},
        {name:'Сеанс №22',done:false},
        {name:'Сеанс №23',done:false},
        {name:'Сеанс №24',done:false},
        {name:'Сеанс №25',done:false},
        {name:'Сеанс №26',done:false},
        {name:'Сеанс №27',done:false},
        {name:'Сеанс №28',done:false},
        {name:'Сеанс №29',done:false},
        {name:'Сеанс №30',done:false},
],    
    cuponsDone:[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],    
    certificateDone:false
},]

